### PR TITLE
Restructure Fundamental APIs

### PR DESCRIPTION
**Pull request by Natanel-Ziv**
- [x] New structure for the fundamental APIs
- [x] moved test for fundamentals to test directory
- [x] added symbol lookup API
- [x] added MarketNews API
- [x] added interface for requesting params 
- [x] added Company news API
- [x] added News Sentiment API
- [x] fixed peers API
- [x] added Basic Financials API
- [x] added Insider Transaction API
- [ ] added Financials As Reported API
- [ ] SEC Filings
- [ ] IPO Calendar

Theses are all the free tier STOCK FUNDAMENTALS APIs

### CODE REVIEW

**Comment by Tsopic** [comment]
Any way you could make these tests run automatically and report in git?

**Comment by Natanel-Ziv** [comment]
Never have done it. I will look into it, if you have a reference that would be great

**Comment by Tsopic** [comment]
https://github.com/stoqey/ib/tree/master/.circleci

just modify this file to use mocha instead of jest ;)

**Comment by ceddybi** [comment]
@Tsopic I think maybe @Natanel-Ziv can first complete this PR, then he can open another PR for CI/CD later in the future

**Comment by Tsopic** [comment]
Okay, but we still should deprecate the old functions. I'm using getPeers in my server, once I upgrade it, it will be breaking change.

**Comment by Natanel-Ziv** [comment]
@Tsopic How do you suggest deprecating?
I can keep the getPeers function but to "route" it to the new one, will that be a satisfying solution?

**Comment by Tsopic** [comment]
@Natanel-Ziv Yeh, think that will do

**Comment by Natanel-Ziv** [comment]
@Tsopic take a look at the latest commit ;)

**Review by Tsopic — APPROVED** [review]

**Comment by Tsopic** [comment]
Looks good ;)

**Comment by Tsopic** [comment]
@Natanel-Ziv can you merge the changes and add other stuff in new pr? I want to add some stuff ;)

**Comment by Natanel-Ziv** [comment]
Sure you can merge

**Comment by Tsopic** [comment]
- [ ] added Financials As Reported API
- [ ] SEC Filings
- [ ] IPO Calendar

removed these from description

**Pull request merged**
