### PR TITLE
Add Recommendation Trends API

### PR DESCRIPTION
**Pull request by Natanel-Ziv**
- [x]  Added Recommendation Trends API
- [x] Updated Readme

@ceddybi If you want I can continue :)

### CODE REVIEW

**Review by ceddybi — APPROVED** [review]
Wow Amazing, please continue ✅🙌🙌🙌💯

**Comment by Natanel-Ziv** [comment]
Do you want me to add also premium APIs?

**Comment by ceddybi** [comment]
@Natanel-Ziv sure please add it too if it's possible, thank you very much

**Comment by ceddybi** [comment]
@Natanel-Ziv please feel free to merge anytime you complete, and a new version will be automatically published to NPM, thank you

**Comment by Natanel-Ziv** [comment]
> @Natanel-Ziv please feel free to merge anytime you complete, and a new version will be automatically published to NPM, thank you

Cool Tnx!
Though I`d love to have a CR :)

**Review by Tsopic — APPROVED** [review]

**Review by ceddybi — APPROVED** [review]

**Pull request merged**
